# cloudbuild.yaml
substitutions:
  _PROJECT_ID: $PROJECT_ID
  _LOWER_PROJECT_ID: ${PROJECT_ID}
  _AR_HOSTNAME: "us-central1-docker.pkg.dev"

  # Define the full image path using ONLY the :latest tag
  _IMAGE_NAME_LATEST: "${_AR_HOSTNAME}/${_LOWER_PROJECT_ID}/task-api:latest"

steps:
  # 1. Build the Docker image (Restored to working array format)
  - id: "Build Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME_LATEST}", "backend/"]

  # 2. PUSH IMAGE
  # Use the OFFICIAL docker builder image
  - id: "Push Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME_LATEST}"]

  # 3. Deploy the :latest image to Cloud Run
  - id: "Deploy to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "task-api"
      - "--image=${_IMAGE_NAME_LATEST}" # Deploy the :latest tagged image
      - "--platform=managed"
      - "--region=us-central1"
      - "--allow-unauthenticated"
      - "--set-env-vars=GOOGLE_CLOUD_PROJECT=${_PROJECT_ID}"

options:
  logging: CLOUD_LOGGING_ONLY
