# cloudbuild.yaml
substitutions:
  _PROJECT_ID: $PROJECT_ID
  _LOWER_PROJECT_ID: ${PROJECT_ID}
  _AR_HOSTNAME: "us-central1-docker.pkg.dev"

  # Define the full tag paths
  _IMAGE_NAME_SHA: "${_AR_HOSTNAME}/${_LOWER_PROJECT_ID}/task-api:$COMMIT_SHA"
  _IMAGE_NAME_LATEST: "${_AR_HOSTNAME}/${_LOWER_PROJECT_ID}/task-api:latest"

steps:
  # 1. Build the Docker image (FIXED TAGGING SYNTAX)
  - id: "Build Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      # Using BASH ensures all variable substitutions work correctly for both tags
      - |
        docker build \
        -t ${_IMAGE_NAME_SHA} \
        -t ${_IMAGE_NAME_LATEST} \
        --cache-from ${_IMAGE_NAME_LATEST} \
        backend/

  # 2. AUTHENTICATION: Configure Docker credentials using GCloud SDK
  - id: "Configure Docker Auth"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

  # 3. PUSH IMAGE: Use the authenticated Docker builder to push the unique tag
  - id: "Push Image"
    name: "gcr.io/cloud-builders/docker"
    args: [
        "push",
        "${_IMAGE_NAME_SHA}", # Push the unique SHA tag
      ]

  # 4. Deploy the unique image to Cloud Run
  - id: "Deploy to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "task-api"
      - "--image=${_IMAGE_NAME_SHA}" # Deploy the unique SHA-tagged image
      - "--platform=managed"
      - "--region=us-central1"
      - "--allow-unauthenticated"
      - "--set-env-vars=GOOGLE_CLOUD_PROJECT=${_PROJECT_ID}"

options:
  logging: CLOUD_LOGGING_ONLY
