# cloudbuild.yaml 
substitutions:
  # Use the system's PROJECT_ID, which may contain uppercase letters
  _PROJECT_ID: $PROJECT_ID
  # Create a lowercase version for Docker tagging
  _LOWER_PROJECT_ID: ${PROJECT_ID}
  # Construct the final image name using the lowercase project ID
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/${_LOWER_PROJECT_ID}/task-api:latest'
steps:
  # 1. Build the Docker image
  - id: 'Build Image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '${_IMAGE_NAME}', 
      'backend/',
      '--cache-from', '${_IMAGE_NAME}' 
    ]

  # 2. Push the newly built image with the :latest tag
  - id: 'Push Image (Latest Tag)'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']
  
  # 3. Deploy the image to Cloud Run using the :latest tag
  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'task-api'
      - '--image=${_IMAGE_NAME}'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY