# cloudbuild.yaml
steps:
  # 1. Build the Docker image
  - id: 'Build Image'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      # Tag the image directly as :latest for the build/cache process
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/task-api:latest', 
      'backend/',
      # CACHING: Use cache from the latest existing image
      '--cache-from', 'us-central1-docker.pkg.dev/$PROJECT_ID/task-api:latest' 
    ]

  # 2. Push the newly built image with the :latest tag
  - id: 'Push Image (Latest Tag)'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/task-api:latest']
  
  # 3. Deploy the image to Cloud Run using the :latest tag
  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'task-api'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/task-api:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

options:
  # COST SAVINGS: Default to the free tier (e2-medium).
  logging: CLOUD_LOGGING_ONLY